logLevel = "DEBUG"
defaultEntryPoints = ["http", "https"]

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]
    [entryPoints.dashboard]
    address = ":8080"

[docker]
endpoint = "unix://var/run/docker.sock"
watch = true
swarmMode = true
exposedByDefault = false
network = "wp"
swarmModeRefreshSeconds = 5

[api]
dashboard = true
entrypoint = "dashboard"

[acme]
email = "YOUR_EMAIL"
storageFile = "acme.json"
entryPoint = "https"
acmeLogging = true
onHostRule = true
caServer = "https://acme-staging-v02.api.letsencrypt.org/directory" # Uncomment/remove if deployed in production

[acme.httpChallenge]
entryPoint = "http"

#[acme.dnsChallenge]
#provider = "digitalocean"
#resolvers = ["1.1.1.1:53", "8.8.8.8:53"]

[[acme.domains]]
main = "MAIN_DOMAIN"