version: '3.7'

services:
  # To avoid connection issue. The name should be unique for every wordpress instance.
  # Alternatively, you can add the internal IP of the db instance.
  db:
    image: mysql:${MYSQL_VERSION:-5.7}
    volumes:
      # During fresh instance, if you are provided with a backup database you can import it.
      # Create a db folder `mkdir db`, put the backup there.
      # Uncomment the line below and it will execute files with extensions .sh, .sql and .sql.gz.
#      - ./db:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${WP_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${WP_DB_NAME:-wordpress}
      MYSQL_USER: ${WP_DB_USER:-wordpress}
      MYSQL_PASSWORD: ${WP_DB_PASSWORD:-wordpress}
    networks:
      - wp

  wordpress:
    image: wordpress:${WP_VERSION:-latest}
    volumes:
      - ./wp-content:/var/www/html/wp-content
    labels:
      - "traefik.frontend.entryPoints=https"
      - "traefik.enable=true"
      - "traefik.weight=10"
      - "traefik.frontend.rule=Host:wordpress.docker.localhost" # Modify sub-domain with your project or preferred name.
      - "traefik.backend=wordpress-localhost" # Define a backend name. Must be unique.
    environment:
      # To avoid connection issue, the db name should be unique.
      # Alternatively, add the internal IP address instead.
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: ${WP_DB_NAME:-wordpress}
      WORDPRESS_DB_USER: ${WP_DB_USER:-wordpress}
      WORDPRESS_DB_PASSWORD: ${WP_DB_PASSWORD:-wordpress}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX:-wp_}
    depends_on:
      - db
    networks:
      - wp

# Network should be created beforehand and set as external.
# This will used across wordpress instance.
networks:
  wp:
    name: wp-traefik-local
    driver: bridge
    external: true